// Known-model registry — the union of baked-in CIM bundles the worker
// recognises (see worker.py::CIM_BUNDLES) plus the demo programmatic
// topology and the "custom" sentinel for uploaded model ids.
//
// The outage catalog for each bundle is auto-generated by
// ops/gen-model-catalog.py from the shipped CIM EQ+TP XML. Do NOT edit
// src/lib/catalogs/*.ts by hand — rerun `make gen-catalogs` instead.

import type { Wscc9Element } from "./wscc9";
import { WSCC9_LINES }           from "./catalogs/wscc9";
import { IEEE14_LINES }          from "./catalogs/ieee14";
import { IEEE39_LINES }          from "./catalogs/ieee39";
import { CIGRE_MV_LINES }        from "./catalogs/cigre_mv";
import { MATPOWER_CASE9_LINES }   from "./catalogs/matpower_case9";
import { MATPOWER_CASE14_LINES }  from "./catalogs/matpower_case14";
import { MATPOWER_CASE300_LINES } from "./catalogs/matpower_case300";

export interface ModelEntry {
  id: string;
  label: string;
  /** Outage-able element catalog for this model. Empty for `demo` and
   *  `custom` — the outage dropdown falls back to a free-text input. */
  outageCatalog: Wscc9Element[];
  /** Short description shown next to the dropdown. */
  hint: string;
  /** Known limitation surfaced as a banner under the model dropdown when
   *  the user picks this entry. Non-fatal — simulation still submits. */
  warning?: string;
}

export const MODELS: ModelEntry[] = [
  {
    id: "wscc9",
    label: "WSCC-9 (9-bus)",
    outageCatalog: WSCC9_LINES,
    hint: "Western System Coordinating Council test system — 9 buses, 3 generators.",
  },
  {
    id: "ieee14",
    label: "IEEE-14 (14-bus, known-divergent)",
    outageCatalog: IEEE14_LINES,
    hint: "IEEE 14-bus test system — the textbook pedagogical case, 14 buses, 5 generators.",
    warning:
      "Upstream dpsim/CIMpp produces NaN on v_n12 after one DP step on the shipped cim-data-src bundle. The submit still works but results will be unusable until the upstream issue lands.",
  },
  {
    id: "ieee39",
    label: "IEEE-39 (New England, 39-bus)",
    outageCatalog: IEEE39_LINES,
    hint: "New England 39-bus reduced transmission system — 34 lines, 12 transformers, 10 generators.",
  },
  {
    id: "cigre_mv",
    label: "CIGRE MV (medium-voltage benchmark)",
    outageCatalog: CIGRE_MV_LINES,
    hint: "CIGRE MV distribution benchmark — 15 buses, DER-friendly scenarios.",
  },
  {
    id: "matpower_case9",
    label: "Matpower case9 (9-bus, profile gap)",
    outageCatalog: MATPOWER_CASE9_LINES,
    hint: "Matpower standard case9 — equivalent topology to WSCC-9 in single-file CIM.",
    warning:
      "dpsim/CIMReader leaves every bus at 0 V on the shipped Matpower CIM export. Topology and outage scenarios load correctly, but DP output is not usable until the profile handling is fixed upstream.",
  },
  {
    id: "matpower_case14",
    label: "Matpower case14 (14-bus, profile gap)",
    outageCatalog: MATPOWER_CASE14_LINES,
    hint: "Matpower standard case14 — IEEE-14 equivalent, single-file CIM.",
    warning:
      "Same Matpower/CIMReader profile gap as case9 — bus voltages come back as 0 V. Topology is correct for diagram / outage UX.",
  },
  {
    id: "matpower_case300",
    label: "Matpower case300 (300-bus, large, profile gap)",
    outageCatalog: MATPOWER_CASE300_LINES,
    hint: "300-bus transmission case — stress test. 304 lines, 107 transformers.",
    warning:
      "Same Matpower/CIMReader profile gap as case9/case14. Good for layout / outage-picker stress tests; results are not physically meaningful today.",
  },
  {
    id: "demo",
    label: "Demo topology (programmatic)",
    outageCatalog: [],
    hint: "Small hand-built circuit the worker constructs in Python. EMT-capable.",
  },
];

/** Lookup helper. Returns undefined for custom/uploaded ids. */
export function findModel(id: string): ModelEntry | undefined {
  return MODELS.find((m) => m.id === id);
}
