/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Readiness probe — returns 200 only when all critical dependencies are reachable: redis (rate-limit + sim store), PG (audit log + user store; skipped when DATABASE_URL unset), and AMQP (worker queue). Returns 503 with the per-component breakdown when any check fails. Point kubernetes readinessProbe at this instead of /healthz. */
        get: operations["get_readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List simulations. Pagination via `?limit=N&offset=N` (default 50, max 500). Optional filters: `?status=queued|running|done|failed|canceled`, `?domain=SP|DP|EMT`, `?model_id=<id>`. Sort via `?sort=simulation_id|created_at|status|domain` + `?order=asc|desc` (default `created_at desc`). Filters + sort require PG — they are ignored on the redis fallback path. */
        get: operations["get_simulations"];
        put?: never;
        /** @description Create a new simulation */
        post: operations["post_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit multiple simulations in one request. Each item is validated + queued independently; the response reports per-item success/failure so a partially-successful batch still delivers the queued sims. Capped at 500 items per request. */
        post: operations["post_bulk_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel a simulation. Sets a redis flag `sim:<id>:canceled` that the worker checks before starting work. For queued jobs the worker acks the AMQP message and moves on. For already-running jobs the cancel is best-effort — the current sim.run() can't be interrupted mid-step, but the post-run logging path skips uploading results when the flag is set. Idempotent: calling twice returns the same response. */
        post: operations["post_cancel_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description v1.2.7 — re-submit a prior simulation under a fresh id. The source simulation is read from redis; its parameters become a new SimulationForm which is parsed through the normal validate + queue path. Useful after a `failed` result (user wants to rerun same params) or to replay a deterministic regression case.
         *
         *     404 if the source id is unknown. 502 when AMQP publish fails. 400 when the replayed params no longer pass validation (e.g. because the referenced model_id has been deleted from file-service).
         *
         *     The new sim has its own id, trace_id, and results_id — nothing ties it back to the source beyond the request that triggered it. Audit log records both ids so forensics can link them.
         */
        post: operations["post_retry_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the details for a simulation */
        get: operations["get_simulation_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["crate_topology_get_topology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body of /readyz so each component's state is machine-readable. */
        ReadyzResponse: {
            ready: boolean;
            redis: boolean;
            postgres: boolean;
            amqp: boolean;
        };
        /**
         * @description Paged list of simulations.
         *
         *     `total` is the full count available on the server (useful for paging UI); `limit` + `offset` echo back the effective query (may be clamped from the request).
         */
        SimulationArray: {
            simulations: components["schemas"]["SimulationSummary"][];
            /**
             * Format: uint64
             * @default 0
             */
            total: number;
            /**
             * Format: uint32
             * @default 0
             */
            limit: number;
            /**
             * Format: uint32
             * @default 0
             */
            offset: number;
        };
        SimulationSummary: {
            /** Format: uint64 */
            simulation_id: number;
            model_id: string;
            simulation_type: components["schemas"]["SimulationType"];
            status?: string | null;
            domain?: components["schemas"]["DomainType"] | null;
            engine?: components["schemas"]["EngineType"] | null;
        };
        /**
         * @description Enum for the various Simulation types
         * @enum {string}
         */
        SimulationType: "Powerflow" | "Outage";
        /**
         * @description Enum for the various Simulation types
         * @enum {string}
         */
        DomainType: "SP" | "DP" | "EMT";
        /**
         * @description Simulation engine selection (Phase 4 dual-engine UX).
         *
         *     dpsim      — native DP/EMT/SP simulator (default, backward compatible). pandapower — CIM → pp.runpp() steady-state only, much faster for PF. both       — runs pandapower first (quick reference) then dpsim; UI can diff the two CSVs.
         * @enum {string}
         */
        EngineType: "dpsim" | "pandapower" | "both";
        /** @description Struct for encapsulation Simulation details */
        Simulation: {
            error: string;
            load_profile_id: string;
            model_id: string;
            results_id: string;
            results_data: string;
            /** Format: uint64 */
            simulation_id: number;
            simulation_type: components["schemas"]["SimulationType"];
            domain: components["schemas"]["DomainType"];
            solver: components["schemas"]["SolverType"];
            /** Format: uint64 */
            timestep: number;
            /** Format: uint64 */
            finaltime: number;
            /** @default  */
            trace_id: string;
            /** @default dpsim */
            engine: components["schemas"]["EngineType"];
        };
        /**
         * @description Enum for the various Solver types
         * @enum {string}
         */
        SolverType: "MNA" | "DAE" | "NRP";
        /**
         * Form for submitting a new Simulation
         * @description ## Parameters: * simulation_type - String - must be one of "Powerflow", "Outage" * load_profile_id - String - must be a valid id that exists in the associated sogno file service * model_id - String - must be a valid id that exists in the associated sogno file service
         */
        SimulationForm: {
            simulation_type: components["schemas"]["SimulationType"];
            model_id: string;
            load_profile_id: string;
            domain: components["schemas"]["DomainType"];
            solver: components["schemas"]["SolverType"];
            /** Format: uint64 */
            timestep: number;
            /** Format: uint64 */
            finaltime: number;
            /** @description Optional — name (mRID or name attribute) of a CIM ACLineSegment to remove before sim.run(). Leave empty / None for a baseline simulation. P3.4 outage MVP. */
            outage_component?: string | null;
            /**
             * Format: double
             * @description Optional — multiplier applied to every CIM EnergyConsumer P/Q before sim.run(). 1.0 = baseline, 1.5 = heavier load, 0.5 = lighter. Worker mutates the SV file so CIMReader sees the scaled values. P3.3 load-profile MVP (scalar, not time-series).
             */
            load_factor?: number | null;
            /** @description Optional — time-series variant of load_factor. Each point is [t_sec, factor]; worker picks an effective scalar (max for Powerflow stress-tests, linearly-interpolated end-of-run value for DP/EMT) and applies it with _apply_load_factor. Per-step time-stepping isn't exposed by dpsim's Python API so this is a pragmatic approximation — see docs/44 §X for the scope note. */
            load_factor_series?: components["schemas"]["LoadFactorPoint"][] | null;
            /**
             * @description Simulation engine (Phase 4). dpsim is backward-compatible default. `pandapower` runs pp.runpp() via the PISA adapter; `both` runs pp first then dpsim so the UI can compare the two. The worker dispatches on `parameters.engine` in the AMQP payload.
             * @default dpsim
             */
            engine: components["schemas"]["EngineType"];
        };
        LoadFactorPoint: {
            /** Format: double */
            t_sec: number;
            /** Format: double */
            factor: number;
        };
        BulkSubmitResponse: {
            /** Format: uint */
            submitted: number;
            /** Format: uint */
            failed: number;
            results: components["schemas"]["BulkSubmitItem"][];
        };
        /** @description Per-item outcome for /simulation/bulk. Either `simulation` is populated (submitted + queued) or `error` is (validation / AMQP failure). `index` mirrors the request-array position so the client can correlate. */
        BulkSubmitItem: {
            /** Format: uint */
            index: number;
            simulation?: components["schemas"]["Simulation"] | null;
            error?: string | null;
            code?: string | null;
        };
        /** @description v1.2.8 — bulk submit request. Typical use: outage sweep or N-1 contingency study (one form per outage component). */
        BulkSubmitRequest: {
            simulations: components["schemas"]["SimulationForm"][];
        };
        /** @description Response body for POST /simulation/<id>/cancel. */
        CancelResponse: {
            /** Format: uint64 */
            simulation_id: number;
            canceled: boolean;
            status: string;
        };
        TopologyResponse: {
            model_id: string;
            buses: string[];
            branches: components["schemas"]["TopologyBranch"][];
        };
        TopologyBranch: {
            name: string;
            bus_from: string;
            bus_to: string;
            /** @description "line" | "transformer" | "switch". */
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    get_simulations: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
                status?: string | null;
                domain?: string | null;
                model_id?: string | null;
                sort?: string | null;
                order?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationArray"];
                };
            };
        };
    };
    post_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationForm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
        };
    };
    post_bulk_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkSubmitRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkSubmitResponse"];
                };
            };
        };
    };
    post_cancel_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
        };
    };
    post_retry_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
        };
    };
    get_simulation_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
        };
    };
    crate_topology_get_topology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
