/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the simulations */
        get: operations["get_simulations"];
        put?: never;
        /** @description Create a new simulation */
        post: operations["post_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the details for a simulation */
        get: operations["get_simulation_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["crate_topology_get_topology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Struct for encapsulation Simulation details */
        SimulationArray: {
            simulations: components["schemas"]["SimulationSummary"][];
        };
        SimulationSummary: {
            /** Format: uint64 */
            simulation_id: number;
            model_id: string;
            simulation_type: components["schemas"]["SimulationType"];
        };
        /**
         * @description Enum for the various Simulation types
         * @enum {string}
         */
        SimulationType: "Powerflow" | "Outage";
        /** @description Struct for encapsulation Simulation details */
        Simulation: {
            error: string;
            load_profile_id: string;
            model_id: string;
            results_id: string;
            results_data: string;
            /** Format: uint64 */
            simulation_id: number;
            simulation_type: components["schemas"]["SimulationType"];
            domain: components["schemas"]["DomainType"];
            solver: components["schemas"]["SolverType"];
            /** Format: uint64 */
            timestep: number;
            /** Format: uint64 */
            finaltime: number;
            /** @default  */
            trace_id: string;
            /** @default dpsim */
            engine: components["schemas"]["EngineType"];
        };
        /**
         * @description Enum for the various Simulation types
         * @enum {string}
         */
        DomainType: "SP" | "DP" | "EMT";
        /**
         * @description Enum for the various Solver types
         * @enum {string}
         */
        SolverType: "MNA" | "DAE" | "NRP";
        /**
         * @description Simulation engine selection (Phase 4 dual-engine UX).
         *
         *     dpsim      — native DP/EMT/SP simulator (default, backward compatible). pandapower — CIM → pp.runpp() steady-state only, much faster for PF. both       — runs pandapower first (quick reference) then dpsim; UI can diff the two CSVs.
         * @enum {string}
         */
        EngineType: "dpsim" | "pandapower" | "both";
        /**
         * Form for submitting a new Simulation
         * @description ## Parameters: * simulation_type - String - must be one of "Powerflow", "Outage" * load_profile_id - String - must be a valid id that exists in the associated sogno file service * model_id - String - must be a valid id that exists in the associated sogno file service
         */
        SimulationForm: {
            simulation_type: components["schemas"]["SimulationType"];
            model_id: string;
            load_profile_id: string;
            domain: components["schemas"]["DomainType"];
            solver: components["schemas"]["SolverType"];
            /** Format: uint64 */
            timestep: number;
            /** Format: uint64 */
            finaltime: number;
            /** @description Optional — name (mRID or name attribute) of a CIM ACLineSegment to remove before sim.run(). Leave empty / None for a baseline simulation. P3.4 outage MVP. */
            outage_component?: string | null;
            /**
             * Format: double
             * @description Optional — multiplier applied to every CIM EnergyConsumer P/Q before sim.run(). 1.0 = baseline, 1.5 = heavier load, 0.5 = lighter. Worker mutates the SV file so CIMReader sees the scaled values. P3.3 load-profile MVP (scalar, not time-series).
             */
            load_factor?: number | null;
            /** @description Optional — time-series variant of load_factor. Each point is [t_sec, factor]; worker picks an effective scalar (max for Powerflow stress-tests, linearly-interpolated end-of-run value for DP/EMT) and applies it with _apply_load_factor. Per-step time-stepping isn't exposed by dpsim's Python API so this is a pragmatic approximation — see docs/44 §X for the scope note. */
            load_factor_series?: components["schemas"]["LoadFactorPoint"][] | null;
            /**
             * @description Simulation engine (Phase 4). dpsim is backward-compatible default. `pandapower` runs pp.runpp() via the PISA adapter; `both` runs pp first then dpsim so the UI can compare the two. The worker dispatches on `parameters.engine` in the AMQP payload.
             * @default dpsim
             */
            engine: components["schemas"]["EngineType"];
        };
        LoadFactorPoint: {
            /** Format: double */
            t_sec: number;
            /** Format: double */
            factor: number;
        };
        TopologyResponse: {
            model_id: string;
            buses: string[];
            branches: components["schemas"]["TopologyBranch"][];
        };
        TopologyBranch: {
            name: string;
            bus_from: string;
            bus_to: string;
            /** @description "line" | "transformer" | "switch". */
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_simulations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationArray"];
                };
            };
        };
    };
    post_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationForm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
        };
    };
    get_simulation_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
        };
    };
    crate_topology_get_topology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
