// Shared element type for every catalog under src/lib/catalogs/. All
// bundle-specific lists (wscc9, ieee14, ieee39, cigre_mv, …) are now
// auto-generated by ops/gen-model-catalog.py from the CIM EQ+TP XML;
// this file only carries the type surface.
//
// The name is kept for backwards compat with session-23 imports; future
// code should prefer `ElementCatalog` from `./models`.

export type Wscc9ElementKind = "line" | "transformer" | "switch";

export interface Wscc9Element {
  name: string;
  busFrom: string;
  busTo: string;
  kind: Wscc9ElementKind;
}
