// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py cigre_mv <EQ XML> --out dpsim-web/src/lib/catalogs/cigre_mv.ts
//
// Source: dpsim/build/_deps/cim-data-src/CIGRE_MV/NEPLAN/CIGRE_MV_no_tapchanger_noLoad1_LeftFeeder_With_LoadFlow_Results/Rootnet_FULL_NE_28J17h_DI.xml, dpsim/build/_deps/cim-data-src/CIGRE_MV/NEPLAN/CIGRE_MV_no_tapchanger_noLoad1_LeftFeeder_With_LoadFlow_Results/Rootnet_FULL_NE_28J17h_EQ.xml, dpsim/build/_deps/cim-data-src/CIGRE_MV/NEPLAN/CIGRE_MV_no_tapchanger_noLoad1_LeftFeeder_With_LoadFlow_Results/Rootnet_FULL_NE_28J17h_SV.xml, dpsim/build/_deps/cim-data-src/CIGRE_MV/NEPLAN/CIGRE_MV_no_tapchanger_noLoad1_LeftFeeder_With_LoadFlow_Results/Rootnet_FULL_NE_28J17h_TP.xml
// Elements: 11  (lines: 10, transformers: 1, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const CIGRE_MV_LINES: Wscc9Element[] = [
  { name: "L1-2", busFrom: "N1", busTo: "N2", kind: "line" },
  { name: "L10-9", busFrom: "N10", busTo: "N9", kind: "line" },
  { name: "L11-10", busFrom: "N11", busTo: "N10", kind: "line" },
  { name: "L2-3", busFrom: "N2", busTo: "N3", kind: "line" },
  { name: "L3-4", busFrom: "N3", busTo: "N4", kind: "line" },
  { name: "L3-8", busFrom: "N3", busTo: "N8", kind: "line" },
  { name: "L4-5", busFrom: "N4", busTo: "N5", kind: "line" },
  { name: "L5-6", busFrom: "N5", busTo: "N6", kind: "line" },
  { name: "L7-8", busFrom: "N8", busTo: "N7", kind: "line" },
  { name: "L8-9", busFrom: "N8", busTo: "N9", kind: "line" },
  { name: "TR0", busFrom: "N0", busTo: "N1", kind: "transformer" },
];
