// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py ieee39 <EQ XML> --out dpsim-web/src/lib/catalogs/ieee39.ts
//
// Source: dpsim/build/_deps/cim-data-src/IEEE-39/Rootnet_FULL_NE_29J10h_DI.xml, dpsim/build/_deps/cim-data-src/IEEE-39/Rootnet_FULL_NE_29J10h_EQ.xml, dpsim/build/_deps/cim-data-src/IEEE-39/Rootnet_FULL_NE_29J10h_SV.xml, dpsim/build/_deps/cim-data-src/IEEE-39/Rootnet_FULL_NE_29J10h_TP.xml
// Elements: 46  (lines: 34, transformers: 12, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const IEEE39_LINES: Wscc9Element[] = [
  { name: "L-01-02", busFrom: "N01", busTo: "N02", kind: "line" },
  { name: "L-01-39", busFrom: "N01", busTo: "N39", kind: "line" },
  { name: "L-02-03", busFrom: "N02", busTo: "N03", kind: "line" },
  { name: "L-02-25", busFrom: "N02", busTo: "N25", kind: "line" },
  { name: "L-03-04", busFrom: "N03", busTo: "N04", kind: "line" },
  { name: "L-03-18", busFrom: "N03", busTo: "N18", kind: "line" },
  { name: "L-04-05", busFrom: "N04", busTo: "N05", kind: "line" },
  { name: "L-04-14", busFrom: "N04", busTo: "N14", kind: "line" },
  { name: "L-05-06", busFrom: "N05", busTo: "N06", kind: "line" },
  { name: "L-05-08", busFrom: "N05", busTo: "N08", kind: "line" },
  { name: "L-06-07", busFrom: "N06", busTo: "N07", kind: "line" },
  { name: "L-06-11", busFrom: "N11", busTo: "N06", kind: "line" },
  { name: "L-07-08", busFrom: "N07", busTo: "N08", kind: "line" },
  { name: "L-08-09", busFrom: "N08", busTo: "N09", kind: "line" },
  { name: "L-09-39", busFrom: "N09", busTo: "N39", kind: "line" },
  { name: "L-10-11", busFrom: "N10", busTo: "N11", kind: "line" },
  { name: "L-10-13", busFrom: "N10", busTo: "N13", kind: "line" },
  { name: "L-13-14", busFrom: "N13", busTo: "N14", kind: "line" },
  { name: "L-14-15", busFrom: "N14", busTo: "N15", kind: "line" },
  { name: "L-15-16", busFrom: "N15", busTo: "N16", kind: "line" },
  { name: "L-16-17", busFrom: "N16", busTo: "N17", kind: "line" },
  { name: "L-16-19", busFrom: "N19", busTo: "N16", kind: "line" },
  { name: "L-16-21", busFrom: "N16", busTo: "N21", kind: "line" },
  { name: "L-16-24", busFrom: "N16", busTo: "N24", kind: "line" },
  { name: "L-17-18", busFrom: "N17", busTo: "N18", kind: "line" },
  { name: "L-17-27", busFrom: "N17", busTo: "N27", kind: "line" },
  { name: "L-21-22", busFrom: "N21", busTo: "N22", kind: "line" },
  { name: "L-22-23", busFrom: "N22", busTo: "N23", kind: "line" },
  { name: "L-23-24", busFrom: "N23", busTo: "N24", kind: "line" },
  { name: "L-25-26", busFrom: "N25", busTo: "N26", kind: "line" },
  { name: "L-26-27", busFrom: "N26", busTo: "N27", kind: "line" },
  { name: "L-26-28", busFrom: "N26", busTo: "N28", kind: "line" },
  { name: "L-26-29", busFrom: "N26", busTo: "N29", kind: "line" },
  { name: "L-28-29", busFrom: "N28", busTo: "N29", kind: "line" },
  { name: "TR-02-30", busFrom: "N02", busTo: "N30", kind: "transformer" },
  { name: "TR-06-31", busFrom: "N06", busTo: "N31", kind: "transformer" },
  { name: "TR-10-32", busFrom: "N10", busTo: "N32", kind: "transformer" },
  { name: "TR-12-11", busFrom: "N12", busTo: "N11", kind: "transformer" },
  { name: "TR-12-13", busFrom: "N12", busTo: "N13", kind: "transformer" },
  { name: "TR-19-20", busFrom: "N19", busTo: "N20", kind: "transformer" },
  { name: "TR-19-33", busFrom: "N19", busTo: "N33", kind: "transformer" },
  { name: "TR-20-34", busFrom: "N20", busTo: "N34", kind: "transformer" },
  { name: "TR-22-35", busFrom: "N22", busTo: "N35", kind: "transformer" },
  { name: "TR-23-36", busFrom: "N23", busTo: "N36", kind: "transformer" },
  { name: "TR-25-37", busFrom: "N25", busTo: "N37", kind: "transformer" },
  { name: "TR-29-38", busFrom: "N29", busTo: "N38", kind: "transformer" },
];
