// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py ieee14 <EQ XML> --out dpsim-web/src/lib/catalogs/ieee14.ts
//
// Source: dpsim/build/_deps/cim-data-src/IEEE-14/Rootnet_FULL_NE_29J09h_DI.xml, dpsim/build/_deps/cim-data-src/IEEE-14/Rootnet_FULL_NE_29J09h_EQ.xml, dpsim/build/_deps/cim-data-src/IEEE-14/Rootnet_FULL_NE_29J09h_SV.xml, dpsim/build/_deps/cim-data-src/IEEE-14/Rootnet_FULL_NE_29J09h_TP.xml
// Elements: 20  (lines: 16, transformers: 4, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const IEEE14_LINES: Wscc9Element[] = [
  { name: "LINE-01-02", busFrom: "Bus 01", busTo: "Bus 02", kind: "line" },
  { name: "LINE-01-05", busFrom: "Bus 01", busTo: "Bus 05", kind: "line" },
  { name: "LINE-02-04", busFrom: "Bus 02", busTo: "Bus 04", kind: "line" },
  { name: "LINE-02-05", busFrom: "Bus 02", busTo: "Bus 05", kind: "line" },
  { name: "LINE-03-02", busFrom: "Bus 03", busTo: "Bus 02", kind: "line" },
  { name: "LINE-03-04", busFrom: "Bus 03", busTo: "Bus 04", kind: "line" },
  { name: "LINE-05-04", busFrom: "Bus 05", busTo: "Bus 04", kind: "line" },
  { name: "LINE-06-11", busFrom: "Bus 06", busTo: "Bus 11", kind: "line" },
  { name: "LINE-06-12", busFrom: "Bus 06", busTo: "Bus 12", kind: "line" },
  { name: "LINE-06-13", busFrom: "Bus 06", busTo: "Bus 13", kind: "line" },
  { name: "LINE-07-09", busFrom: "Bus 07", busTo: "Bus 09", kind: "line" },
  { name: "LINE-09-10", busFrom: "Bus 09", busTo: "Bus 10", kind: "line" },
  { name: "LINE-09-14", busFrom: "Bus 09", busTo: "Bus 14", kind: "line" },
  { name: "LINE-11-10", busFrom: "Bus 11", busTo: "Bus 10", kind: "line" },
  { name: "LINE-12-13", busFrom: "Bus 12", busTo: "Bus 13", kind: "line" },
  { name: "LINE-14-13", busFrom: "Bus 14", busTo: "Bus 13", kind: "line" },
  { name: "TR-04-07", busFrom: "Bus 04", busTo: "Bus 07", kind: "transformer" },
  { name: "TR-04-09", busFrom: "Bus 04", busTo: "Bus 09", kind: "transformer" },
  { name: "TR-05-06", busFrom: "Bus 05", busTo: "Bus 06", kind: "transformer" },
  { name: "TR-08-07", busFrom: "Bus 08", busTo: "Bus 07", kind: "transformer" },
];
