// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py matpower_case14 <EQ XML> --out dpsim-web/src/lib/catalogs/matpower_case14.ts
//
// Source: dpsim/build/_deps/cim-data-src/Matpower_cases/case14.xml
// Elements: 20  (lines: 16, transformers: 4, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const MATPOWER_CASE14_LINES: Wscc9Element[] = [
  { name: "TN10_T3PiLine_10-11", busFrom: "TN10", busTo: "TN11", kind: "line" },
  { name: "TN12_T3PiLine_12-13", busFrom: "TN12", busTo: "TN13", kind: "line" },
  { name: "TN13_T4PiLine_13-14", busFrom: "TN13", busTo: "TN14", kind: "line" },
  { name: "TN1_T2PiLine_1-2", busFrom: "TN1", busTo: "TN2", kind: "line" },
  { name: "TN1_T3PiLine_1-5", busFrom: "TN1", busTo: "TN5", kind: "line" },
  { name: "TN2_T4PiLine_2-3", busFrom: "TN2", busTo: "TN3", kind: "line" },
  { name: "TN2_T5PiLine_2-4", busFrom: "TN2", busTo: "TN4", kind: "line" },
  { name: "TN2_T6PiLine_2-5", busFrom: "TN2", busTo: "TN5", kind: "line" },
  { name: "TN3_T4PiLine_3-4", busFrom: "TN3", busTo: "TN4", kind: "line" },
  { name: "TN4_T4PiLine_4-5", busFrom: "TN4", busTo: "TN5", kind: "line" },
  { name: "TN6_T4PiLine_6-11", busFrom: "TN6", busTo: "TN11", kind: "line" },
  { name: "TN6_T5PiLine_6-12", busFrom: "TN6", busTo: "TN12", kind: "line" },
  { name: "TN6_T6PiLine_6-13", busFrom: "TN6", busTo: "TN13", kind: "line" },
  { name: "TN7_T4PiLine_7-9", busFrom: "TN7", busTo: "TN9", kind: "line" },
  { name: "TN9_T5PiLine_9-10", busFrom: "TN9", busTo: "TN10", kind: "line" },
  { name: "TN9_T6PiLine_9-14", busFrom: "TN9", busTo: "TN14", kind: "line" },
  { name: "TN4_T5PwerTrafo_4-7", busFrom: "TN4", busTo: "TN7", kind: "transformer" },
  { name: "TN4_T6PwerTrafo_4-9", busFrom: "TN4", busTo: "TN9", kind: "transformer" },
  { name: "TN5_T5PwerTrafo_5-6", busFrom: "TN5", busTo: "TN6", kind: "transformer" },
  { name: "TN7_T3PwerTrafo_7-8", busFrom: "TN7", busTo: "TN8", kind: "transformer" },
];
