// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py matpower_case9 <EQ XML> --out dpsim-web/src/lib/catalogs/matpower_case9.ts
//
// Source: dpsim/build/_deps/cim-data-src/Matpower_cases/case9.xml
// Elements: 9  (lines: 9, transformers: 0, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const MATPOWER_CASE9_LINES: Wscc9Element[] = [
  { name: "TN1_T2PiLine_1-4", busFrom: "TN1", busTo: "TN4", kind: "line" },
  { name: "TN3_T1PiLine_3-6", busFrom: "TN3", busTo: "TN6", kind: "line" },
  { name: "TN4_T2PiLine_4-5", busFrom: "TN4", busTo: "TN5", kind: "line" },
  { name: "TN5_T3PiLine_5-6", busFrom: "TN5", busTo: "TN6", kind: "line" },
  { name: "TN6_T3PiLine_6-7", busFrom: "TN6", busTo: "TN7", kind: "line" },
  { name: "TN7_T3PiLine_7-8", busFrom: "TN7", busTo: "TN8", kind: "line" },
  { name: "TN8_T2PiLine_8-2", busFrom: "TN8", busTo: "TN2", kind: "line" },
  { name: "TN8_T3PiLine_8-9", busFrom: "TN8", busTo: "TN9", kind: "line" },
  { name: "TN9_T3PiLine_9-4", busFrom: "TN9", busTo: "TN4", kind: "line" },
];
