// Auto-generated by ops/gen-model-catalog.py — do NOT edit by hand.
// Regenerate: `make gen-catalogs` or
//   python3 ops/gen-model-catalog.py wscc9 <EQ XML> --out dpsim-web/src/lib/catalogs/wscc9.ts
//
// Source: dpsim/build/_deps/cim-data-src/WSCC-09/WSCC-09/WSCC-09_DI.xml, dpsim/build/_deps/cim-data-src/WSCC-09/WSCC-09/WSCC-09_EQ.xml, dpsim/build/_deps/cim-data-src/WSCC-09/WSCC-09/WSCC-09_SV.xml, dpsim/build/_deps/cim-data-src/WSCC-09/WSCC-09/WSCC-09_TP.xml
// Elements: 9  (lines: 6, transformers: 3, switches: 0)

import type { Wscc9Element } from "../wscc9";

export const WSCC9_LINES: Wscc9Element[] = [
  { name: "LINE54", busFrom: "BUS5", busTo: "BUS4", kind: "line" },
  { name: "LINE64", busFrom: "BUS6", busTo: "BUS4", kind: "line" },
  { name: "LINE75", busFrom: "BUS7", busTo: "BUS5", kind: "line" },
  { name: "LINE78", busFrom: "BUS7", busTo: "BUS8", kind: "line" },
  { name: "LINE89", busFrom: "BUS9", busTo: "BUS8", kind: "line" },
  { name: "LINE96", busFrom: "BUS9", busTo: "BUS6", kind: "line" },
  { name: "TR14", busFrom: "BUS1", busTo: "BUS4", kind: "transformer" },
  { name: "TR27", busFrom: "BUS2", busTo: "BUS7", kind: "transformer" },
  { name: "TR39", busFrom: "BUS3", busTo: "BUS9", kind: "transformer" },
];
